//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wildfire.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wildfire.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;fireRegions&gt;
        ///  &lt;fireRegion alias=&quot;wfRegion3&quot; probability=&quot;5&quot; density=&quot;7&quot;&gt;
        ///    &lt;perimeterPoints&gt;
        ///      &lt;point x=&quot;-432.9599&quot; y=&quot;5912.776&quot; z=&quot;38.16785&quot; /&gt;
        ///      &lt;point x=&quot;-489.9005&quot; y=&quot;5828.227&quot; z=&quot;40.22844&quot; /&gt;
        ///      &lt;point x=&quot;-528.5942&quot; y=&quot;5743.928&quot; z=&quot;41.81195&quot; /&gt;
        ///      &lt;point x=&quot;-556.9196&quot; y=&quot;5677.622&quot; z=&quot;45.23441&quot; /&gt;
        ///      &lt;point x=&quot;-588.0683&quot; y=&quot;5618.491&quot; z=&quot;44.86887&quot; /&gt;
        ///      &lt;point x=&quot;-631.0748&quot; y=&quot;5569.942&quot; z=&quot;44.97806&quot; /&gt;
        ///      &lt;point x=&quot;-700.8104&quot; y=&quot;5522.659&quot; z=&quot;44.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fireregions {
            get {
                return ResourceManager.GetString("fireregions", resourceCulture);
            }
        }
    }
}
